name: Python Build on macOS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # You can specify e.g., '3.11' if needed

      - name: Install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
        shell: bash  # Ensure bash shell for source to work

      - name: Run Python Script
        run: |
          source venv/bin/activate
          python main.py
        shell: bash
